---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/info-widgets/

- resources:
    cpu: true
    memory: true
    network: true
    uptime: true

- resources:
    label: Root
    disk: /

- resources:
    label: ZFS Pool
    disk: /mnt/zpool0
